<?php
use Migrations\AbstractSeed;

/**
 * Products seed.
 */
class ProductsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $datetime = date('Y-m-d H:i:s');
        // fakerインスタンスを生成する
        $data = [
            [
                'category_id' => 1,
                'name' => 'フライパン',
                'price' => 13750,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' => 20,
                'height' => null,
                'thickness' => 6,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 1,
                'name' => 'フライパン',
                'price' => 15180,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' => 24,
                'height' => null,
                'thickness' => 6,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 1,
                'name' => 'フライパン',
                'price' => 17380,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' => 28,
                'height' => null,
                'thickness' => 6,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 1,
                'name' => 'フライパン',
                'price' => 18700,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' => 30,
                'height' => null,
                'thickness' => 6,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 2,
                'name' => 'フライパン（IH対応）',
                'price' => 16280,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' => 20,
                'height' => null,
                'thickness' => 6,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 2,
                'name' => 'フライパン（IH対応）',
                'price' => 17380,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' => 24,
                'height' => null,
                'thickness' => 6,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 2,
                'name' => 'フライパン（IH対応）',
                'price' => 19580,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' => 28,
                'height' => null,
                'thickness' => 6,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 3,
                'name' => 'ディープパン（深型フライパン）',
                'price' => 22880,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' => 28,
                'height' => null,
                'thickness' => 7,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 4,
                'name' => 'ディープパン（深型フライパン、IH対応）',
                'price' => 26180,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' => 28,
                'height' => null,
                'thickness' => 7,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 5,
                'name' => 'シチューポット（深型両手鍋）',
                'price' => 18920,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' => 20,
                'height' => null,
                'thickness' => 6,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 5,
                'name' => 'シチューポット（深型両手鍋）',
                'price' => 22880,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' => 24,
                'height' => null,
                'thickness' => 6,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 6,
                'name' => 'シチューポット（深型両手鍋、IH対応）',
                'price' => 26180,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' => 24,
                'height' => null,
                'thickness' => 6,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 7,
                'name' => 'シチューパン（浅型両手鍋）',
                'price' => 20680,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' => 24,
                'height' => null,
                'thickness' => 6,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 7,
                'name' => 'シチューパン（浅型両手鍋）',
                'price' => 23650,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' => 28,
                'height' => null,
                'thickness' => 6,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 8,
                'name' => 'シチューパン（浅型両手鍋、IH対応）',
                'price' => 27200,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' => 24,
                'height' => null,
                'thickness' => 6,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 9,
                'name' => 'グリル',
                'price' => 13750,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => '26×26',
                'size_circle' => null,
                'height' => null,
                'thickness' => 6,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 10,
                'name' => 'グリル（IH対応）',
                'price' => 16280,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => '26×26',
                'size_circle' => null,
                'height' => null,
                'thickness' => 6,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 11,
                'name' => 'ソースポット（片手鍋）',
                'price' => 15180,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' => 16,
                'height' => null,
                'thickness' => 6,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 12,
                'name' => 'ソースポット（片手鍋、IH対応）',
                'price' => 17380,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' => 16,
                'height' => null,
                'thickness' => 6,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 13,
                'name' => 'プレートグリル',
                'price' => 19800,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => '46×25',
                'size_circle' => null,
                'height' => null,
                'thickness' => 6,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 14,
                'name' => 'オーバルローストパン（楕円形深型鍋）',
                'price' => 31200,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' => 36,
                'height' => 24,
                'thickness' => 6,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 15,
                'name' => 'エッグ＆スイート',
                'price' => 3200,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' =>14,
                'height' => null,
                'thickness' => 6,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 16,
                'name' => 'プロテクター',
                'price' => 2500,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => '17×17',
                'size_circle' => null,
                'height' => 3,
                'thickness' => null,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 17,
                'name' => 'ガラス蓋',
                'price' => 3200,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' => 20,
                'height' => null,
                'thickness' => null,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 17,
                'name' => 'ガラス蓋',
                'price' => 3500,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' => 24,
                'height' => null,
                'thickness' => null,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'category_id' => 17,
                'name' => 'ガラス蓋',
                'price' => 3900,
                'units_in_stock' => 10,
                'number_of_units_sold' => 1,
                'size_rectangle' => null,
                'size_circle' => 28,
                'height' => null,
                'thickness' => null,
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],

        ];

        $table = $this->table('products');
        $table->insert($data)->save();
    }
}
